"""
evc_deck.py — parser for VB .evc scenario input decks (New Gopo Tunnel).

A deck is ~90 lines of scalars. It is the INPUT to evc_engine.py (which
generates occupant trajectories) — NOT a trajectory file itself.

Key line map (1-indexed), verified against the 9 sample decks:
  L1   tunnel name
  L3   fire anchor reference (matches the FDB fire coordinate)
  L60  Fire_Point , <pos> , <h>
  L63  <pos> , <anchor> , <anchor>   (trailing value = FDB fire coordinate)
  L64  fire position for this P-scenario  -> generated by evc_engine, read here
  L65  vehicle count           (the CONGEST line-65 value)
  L68  HRR [MW]
  L74  fire load param
Occupant mix: L11-16 counts, L24-30 percentages (sum ~100).

Nothing about the fire layout is hardcoded: the per-scenario fire position is
read from L64 (the value your engine generates), and the FDB fire anchor is read
from L63. Both are properties of the deck/field, not assumptions baked into this
parser.
"""
import os, re

def _num(s):
    m = re.findall(r'[-+]?\d*\.?\d+', s)
    return float(m[0]) if m else None

class EvcDeck:
    def __init__(self, path):
        self.path = path
        self.stem = os.path.basename(path).replace('.evc', '')
        self.cls, self.pscen = self.stem.split('_')        # e.g. '030CFV0', 'P1'
        L = open(path, encoding='ascii', errors='replace').read().replace('\r', '').split('\n')
        self.lines = L
        g = lambda n: L[n-1].strip() if n-1 < len(L) else ''
        self.tunnel = g(1)
        self.fire_pos = _num(g(64))          # generated by evc_engine, read here
        # FDB fire anchor: trailing value of L63 ("<pos> , <anchor> , <anchor>")
        l63 = [p.strip() for p in g(63).split(',')]
        self.fdb_fire_anchor = _num(l63[-1]) if l63 and l63[-1] else None
        self.vehicle_count = _num(g(65))
        self.hrr_mw = _num(g(68))
        self.fire_load = _num(g(74))
        self.occ_counts = [_num(g(n)) for n in range(11, 17)]
        self.occ_pct = [_num(g(n)) for n in range(24, 31)]

    def fdb_x(self, tunnel_x, anchor=None):
        """Map an occupant's tunnel x to the class-FDB x coordinate by anchoring
        this scenario's fire to the FDB fire location. `anchor` defaults to the
        value declared in this deck (L63); pass the FDB header's own fire
        midpoint to anchor against the field directly.
        NOTE: assumes occupant x shares the deck's fire_pos frame; the exact
        origin/sign must be confirmed against evc_engine's output frame."""
        a = self.fdb_fire_anchor if anchor is None else anchor
        return a + (tunnel_x - self.fire_pos)

    def __repr__(self):
        return (f"<EvcDeck {self.stem} HRR={self.hrr_mw}MW fire@{self.fire_pos}m "
                f"veh={self.vehicle_count} load={self.fire_load}>")