"""
fed_eqfatal_model.py  (v2 — exp/Purser model, corrected)
=========================================================
FED (Fractional Effective Dose) and EQ_Fatal model for the tunnel-evacuation
engine in the VB6 program (QRA_Road), reconstructed from:

  1. Ghidra decompilation of the FED routines FUN_004956E0 / FUN_00497950
     (the two functions the .SET writers call; they share one model applied to
     two occupant arrays, DAT_004a60b4 and DAT_004a60d0).
  2. Float constants decoded directly from the binary (IEEE-754).
  3. Numerical validation against the real .SET output (020CFV0_P1, 332 occupant
     records; 020CFV0_P3 as a no-exposure control).

================================================================================
CORRECTION OF A PRIOR MISTAKE (read this if you saw v1)
================================================================================
v1 of this file asserted the model was "PURELY LINEAR ... no exp/log/pow ...
this rules out the Purser probit." THAT WAS WRONG. It was based on an FPU-opcode
scan of the WRONG function (a data-marshaller). VB6 compiles exp() to the
runtime call rtcExp, NOT an inline FPU opcode, so the scan was structurally
blind to exactly what it concluded was absent.

The real FED routines contain rtcExp and __vbaVarPow throughout. The model is
the exp-based Purser/SFPE family, NOT linear additive. The v1 FITTED_COEFFS
(linear least-squares, R^2 as low as 0.40) were a linear surrogate fitted to
data generated by an exponential process — which is why they fit poorly.

================================================================================
WHAT IS CONFIRMED vs. UNRESOLVED  (be honest about this when using the model)
================================================================================
CONFIRMED (formula form + binary constants + fit against .SET ground truth):

  HEAT term  -> SET column FED4
      rate = exp(0.0273 * T_degC - 5.1849)
      Validated: FED4 = k * rate * t_min, R^2 = 0.76 vs real .SET (single k).
      (Ceiling <1.0 is the snapshot-vs-trajectory limit: .SET gives endpoint
       concentrations, not the true per-timestep path integral.)

  CO term    -> SET column FED2
      rate = (CO_ppm**1.036 / 36177.26) * RMV   [ /7.1 when flag==0 ]
      RMV  = exp(0.1903 * CO2_pct + 2.004)
      Validated: FED2 = k * rate * t_min, R^2 = 0.74 vs real .SET.
      NOTE: in validated scenarios CO2 stays ~0, so RMV is effectively the
      constant exp(2.004); the CO2 coupling is real in the binary but DORMANT
      when CO2 is low. The CO2-coupling and the /7.1 flag could not be told
      apart from CO2~0 data; see FLAG note below.

  FED_Total  -> SET column FED1 (col 24). Confirmed: FED1 = FED2+FED4+FED7
      exactly in the .SET (cols FED3/5/6 are unused zeros).

DORMANT (constants known from binary; NOT calibrated — scenario didn't exercise):

  O2 term    -> exp(0.5189 * X - 6.1623) with the 20.72 constant pairing to the
      O2 ambient baseline (so X is an O2-depletion measure). In the 020 scenario
      O2 barely moves (20.18–20.95), so this term ~0 and cannot be fit here.
      Included with binary constants but OFF by default until a high-depletion
      .SET exists to validate the exact depletion form and guard.

UNRESOLVED:

  FED7       -> SET column 30. Small (<=0.035), present in ~145/332 records.
      Fits NOTHING tried (soot, 1/visibility, col23, the 80/vis^1.33 power term,
      time-alone) above R^2=0.04. Almost certainly a trajectory-dependent term
      that a single endpoint snapshot cannot reconstruct. Left as a documented
      placeholder; DO NOT trust the FED7 value. It is a minor contributor.

THE FLAG (DAT_004a6000, default 0):
  A run-constant global that selects between two constant-sets; its fingerprint
  is dividing the CO RMV by 7.1 (flag==0) vs not (flag!=0). exp(2.004)/7.1 ≈
  exp(0.0101), i.e. the flag==0 path ≈ the classic Purser CO coefficient, so a
  prior "exp(...+0.0101), no /7.1" formula was an accidental algebraic twin of
  flag==0. Resolve empirically: if VB CO dose ~ old Python, flag==0 (keep
  co_rmv_div_7_1=True, the default).
"""
from __future__ import annotations
import numpy as np

# ============================================================================
# PART 1 — VERIFIED FED MODEL (exp / Purser)
# ============================================================================

# --- Binary constants (decoded from FUN_004956E0; do not edit) -------------
# CO term
CO_CONC_POW   = 1.036       # exponent on CO ppm
CO_DOSE_DIV   = 36177.26    # CO dose divisor          (v1 used 35000 — wrong)
CO_RMV_SLOPE  = 0.1903      # RMV exponent slope on CO2
CO_RMV_ADD    = 2.004       # RMV exponent add const   (v1/old-Py used 0.0101)
CO_RMV_DIV    = 7.1         # applied to RMV when flag==0

# Heat term
HEAT_SLOPE    = 0.0273
HEAT_SUB      = 5.1849

# O2 term (DORMANT — constants from binary, form/guard not yet validated)
O2_SLOPE      = 0.5189
O2_SUB        = 6.1623
O2_AMBIENT    = 20.72       # the 20.721 constant ~ O2 baseline -> depletion form

# Guards — from the full FUN_004956e0 listing (MOV.txt), cross-checked vs .SET
CO_GUARD      = 0.0         # CO term active when CO != 0  (guard: CO != 0)
HEAT_GUARD_LO = 40.0        # heat term active when T > 40 degC.
                            # GUARD SENSE CORRECTED (June 2026): the decompile loads
                            # INTEGER 40 (0x28, VT_I2) and the exp block sits inside
                            # `If Temp > 40 Then` (FUN_004956E0 / FUN_00497950). The
                            # earlier `T < 40` reading was inverted; it gave every
                            # cool-air occupant a spurious ~0.01/min dose and zeroed
                            # the hot-zone dose, compressing the FED distribution.
                            # Purser's ~40 degC convective threshold and the polarised
                            # VB output distribution both agree with T > 40.

# .SET / FDB conventions confirmed from the files
SET_COL = {  # 0-based column indices in the .SET row
    "time_s": 7, "temp": 17, "soot": 18, "co": 19, "o2": 20,
    "vis": 21, "co2": 22, "co23": 23,
    "FED_total": 24, "FED_CO": 25, "FED_unused3": 26,
    "FED_heat": 27, "FED_unused5": 28, "FED_unused6": 29, "FED7": 30,
}
FDB_DT = 30.0  # FDB sampling interval (s); SET time col is in seconds


def fed_rate(co_ppm, co2_pct, temp_c, o2_pct=None,
             co_rmv_div_7_1=True, include_o2=False):
    """Per-occupant FED RATES (per minute), vectorised. Multiply by exposure
    minutes and accumulate. Exp/Purser form — matches the binary.

    Returns dict: FED_CO, FED_heat (confirmed); FED_O2 (only if include_o2);
    FED7 is NOT produced here (unresolved — see module docstring).
    """
    co  = np.asarray(co_ppm,  dtype=float)
    co2 = np.asarray(co2_pct, dtype=float)
    T   = np.asarray(temp_c,  dtype=float)

    # CO (FED2): (CO^1.036 / 36177.26) * exp(0.1903*CO2 + 2.004) [/7.1]
    rmv = np.exp(CO_RMV_SLOPE * co2 + CO_RMV_ADD)
    if co_rmv_div_7_1:
        rmv = rmv / CO_RMV_DIV
    r_co = np.where(co != CO_GUARD, (co ** CO_CONC_POW) / CO_DOSE_DIV * rmv, 0.0)

    # HEAT (FED4): exp(0.0273*T - 5.1849), active when T > 40 (If Temp > 40 Then)
    r_heat = np.where(T > HEAT_GUARD_LO, np.exp(HEAT_SLOPE * T - HEAT_SUB), 0.0)

    out = {"FED_CO": r_co, "FED_heat": r_heat}

    if include_o2:
        if o2_pct is None:
            raise ValueError("include_o2=True requires o2_pct")
        o2 = np.asarray(o2_pct, dtype=float)
        depl = np.maximum(O2_AMBIENT - o2, 0.0)   # depletion form (UNVALIDATED)
        out["FED_O2"] = np.exp(O2_SLOPE * depl - O2_SUB)  # dormant; verify before trusting

    return out


def accumulate_fed(exposure_timeseries, dt_seconds=FDB_DT,
                   co_rmv_div_7_1=True, include_o2=False):
    """Integrate FED over one occupant's exposure history.

    exposure_timeseries: iterable of (co_ppm, co2_pct, temp_c, o2_pct) per step.
    Returns (fed_total, components). fed_total = sum of confirmed components
    (CO + heat [+ O2 if enabled]); FED7 is omitted (unresolved).
    """
    dt_min = dt_seconds / 60.0
    comp = {"FED_CO": 0.0, "FED_heat": 0.0}
    if include_o2:
        comp["FED_O2"] = 0.0
    for step in exposure_timeseries:
        co, co2, temp = step[0], step[1], step[2]
        o2 = step[3] if len(step) > 3 else None
        r = fed_rate(co, co2, temp, o2, co_rmv_div_7_1, include_o2)
        for k in comp:
            comp[k] += float(r[k]) * dt_min
    return sum(comp.values()), comp


# ============================================================================
# PART 2 — RETAINED FROM v1 (unrelated to the FED-form error; left intact)
# ============================================================================
# Jin (1978) walking-speed-in-smoke. These constants are real and independent
# of the FED model; the v1 read of them was not implicated in the exp error.
JIN_SLOPE_IRRITANT    = -0.44
JIN_SLOPE_NONIRRITANT = -0.22
JIN_INTERCEPT_A       = 8.42
JIN_INTERCEPT_B       = 6.13


def walking_speed(base_speed: float, Ks: float, irritant: bool = True) -> float:
    """Jin walking-speed reduction in smoke. Ks = extinction coeff (1/m)."""
    slope = JIN_SLOPE_IRRITANT if irritant else JIN_SLOPE_NONIRRITANT
    return max(base_speed + slope * Ks, 0.1)


def soot_to_extinction(soot_kg_m3, mass_extinction_coeff=8700.0):
    """FDB SOOT mass conc (kg/m^3) -> extinction coeff Ks (1/m)."""
    return mass_extinction_coeff * np.asarray(soot_kg_m3, dtype=float)


def eq_fatal(occupant_fed_totals, clip=True):
    """Scenario EQ_Fatal = expected-fatality sum over occupants. clip caps each
    occupant at 1.0. Zero-exposure scenarios give exactly 0.0."""
    fed = np.asarray(occupant_fed_totals, dtype=float)
    contrib = np.clip(fed, 0.0, 1.0) if clip else np.maximum(fed, 0.0)
    return float(contrib.sum())


def risk_index(frequency_per_yr, eq_fatal_value):
    """Per-scenario Risk Index = Frequency/yr * EQ_Fatal."""
    return frequency_per_yr * eq_fatal_value


# ============================================================================
# PART 3 — VALIDATION HARNESS (reproduces the fits used to confirm the model)
# ============================================================================
def validate_against_set(set_path, co_rmv_div_7_1=True):
    """Fit confirmed rates against a real .SET file; prints per-term R^2.
    Use this whenever you get a new .SET to re-check the bindings/flag."""
    rows = []
    for line in open(set_path, encoding="latin-1"):
        p = line.split()
        if len(p) >= 31:
            rows.append([float(x) for x in p[:31]])
    a = np.array(rows)
    if a.size == 0:
        print(f"{set_path}: no parseable rows"); return
    t = a[:, SET_COL["time_s"]] / 60.0
    m = a[:, SET_COL["FED_total"]] > 0
    if m.sum() == 0:
        print(f"{set_path}: no exposed occupants (control scenario)"); return

    def r2(rate, F):
        x = (rate * t)[m]; y = F[m]
        if np.dot(x, x) == 0: return float("nan"), float("nan")
        k = np.dot(x, y) / np.dot(x, x)
        return k, 1 - np.sum((y - k * x) ** 2) / np.sum((y - y.mean()) ** 2)

    rt = fed_rate(a[:, SET_COL["co"]], a[:, SET_COL["co2"]],
                  a[:, SET_COL["temp"]], co_rmv_div_7_1=co_rmv_div_7_1)
    k_co, r2_co     = r2(rt["FED_CO"],   a[:, SET_COL["FED_CO"]])
    k_ht, r2_ht     = r2(rt["FED_heat"], a[:, SET_COL["FED_heat"]])
    print(f"{set_path}: exposed={int(m.sum())}/{len(a)}")
    print(f"  CO   -> FED2: k={k_co:.4g}  R2={r2_co:+.3f}")
    print(f"  heat -> FED4: k={k_ht:.4g}  R2={r2_ht:+.3f}")


if __name__ == "__main__":
    demo = [  # co_ppm, co2_pct, temp_c, o2_pct  per 30 s
        (300.0, 0.3, 45.0, 20.6),
        (500.0, 0.5, 60.0, 20.2),
        (800.0, 0.68, 90.0, 19.8),
    ]
    fed, comp = accumulate_fed(demo)
    print("Demo FED total:", round(fed, 4))
    print("Components:", {k: round(v, 4) for k, v in comp.items()})
    print("EQ_Fatal (1 occupant):", eq_fatal([fed]))

